export const logoFiles = [
  "1.png",
  "10.png",
  "11.png",
  "13-logo.jpg",
  "2 (1).png",
  "2.png",
  "3 (1).png",
  "3.png",
  "4.png",
  "5 (1).png",
  "5.png",
  "6.png",
  "7.png",
  "8 (1).png",
  "8.png",
  "8PM.png",
  "9 (1).png",
  "9.png",
  "Adda52.png",
  "Anytime-Fitness.png",
  "Apollo-pharmacy.png",
  "Balaji-Logo-1.png",
  "CII.png",
  "Divine-Solitaires-3.png",
  "Fortis.png",
  "Gleneagles-Hospitals-3.png",
  "HDFC.png",
  "HERO.png",
  "Health-Ways-Dairy.png",
  "Leela-Ambience-convention-hotel.png",
  "MANKIND-PHARMA-3.png",
  "Magic-Moments.png",
  "Paras.png",
  "Shiftpurple.png",
  "Topps-Logo-1.png",
  "Untitled-1.png",
  "newyukti.png",
  "nh-logo-2.jpg",
  "rr-logo.png",
  "ss-logo.jpg"
];
